environment:
  matrix:
  - nodejs_version: "0.10"
    jsdom_version: "3"
  - nodejs_version: "0.12"
    jsdom_version: "3"
  - nodejs_version: "4"
    jsdom_version: "3"
  - nodejs_version: "4"
    jsdom_version: "7"
  - nodejs_version: "5"
    jsdom_version: "3"
  - nodejs_version: "5"
    jsdom_version: "7"

install:
  - ps: Install-Product node $env:nodejs_version
  - npm i -g npm
  - npm i jsdom@%jsdom_version%
  - npm i

test_script:
  - node --version
  - npm --version
  - npm test

build: off
