#!/usr/bin/env node

require.paths.unshift(__dirname + "/deps/buster-util/lib");
require.paths.unshift(__dirname + "/deps/buster-assert/lib");
require.paths.unshift(__dirname + "/deps/buster-object-format/lib");
require.paths.unshift(__dirname + "/deps/buster-event-emitter/lib");
require.paths.unshift(__dirname + "/deps/sinon-js/lib");
require.paths.unshift(__dirname + "/deps/sinon-buster/lib");
require.paths.unshift(__dirname + "/lib");
require("sinon-buster");

require("./doc/samples/test-case");