#!/usr/bin/env node

require.paths.unshift(__dirname + "/deps/buster-util/lib");
require.paths.unshift(__dirname + "/deps/buster-assert/lib");
require.paths.unshift(__dirname + "/deps/buster-object-format/lib");
require.paths.unshift(__dirname + "/deps/buster-event-emitter/lib");
require.paths.unshift(__dirname + "/test");
require.paths.unshift(__dirname + "/lib");

var sys = require("sys");
var fs = require("fs");
var path = require("path");

require("buster-assert").format = require("buster-object-format").ascii;
testDir("test");
var filter = !!process.argv[2] ? new RegExp(process.argv[2]) : null;

function testDir(dir) {
    fs.readdir(dir, function (err, files) {
        if (!files) {
            return;
        }

        files.forEach(function (file) {
            var fullPath = path.join(dir, file);

            fs.stat(fullPath, function (err, stat) {
                if (!stat) {
                    return;
                }

                if (stat.isDirectory()) {
                    testDir(fullPath);
                } else {
                    if (/\.js$/.test(file) && !/browser/.test(fullPath) &&
                        (!filter || filter.test(fullPath))) {
                        require("./" + fullPath.replace(/\.js$/, ""));
                    }
                }
            });
        });
    });
}
