#!/usr/bin/env node
require.paths.unshift(__dirname + "/lib");
var buster = require("buster-test");
require("sinon-buster");

buster.filteredRunner(__dirname + "/doc", {
    filter: process.argv[2],
    color: true,
    bright: true,
    failOnNoAssertions: false
});
