#!/usr/bin/env node
require("buster-assert").format = require("buster-format").ascii;

require("sinon").config = {
    useFakeTimers: true,
    useFakeServer: false
};

var testDir = require("buster-test/runner");
testDir("test", process.argv[2] && new RegExp(process.argv[2]));
